joint_0: "hl_hip"
joint_1: "hl_knee"
joint_2: "hl_yaw"
joint_3: "fl_hip"
joint_4: "fl_knee"
joint_5: "fl_yaw"
joint_6: "hr_hip"
joint_7: "hr_knee"
joint_8: "hr_yaw"
joint_9: "fr_hip"
joint_10: "fr_knee"
joint_11: "fr_yaw"

touchdown_0: "fl_td"
touchdown_1: "fr_td"
touchdown_2: "hl_td"
touchdown_3: "hr_td"

imu: "qr.res.imu"
